pravda_urls = ["https://www.pravda.com.ua/news/date_08022026/",
                   "https://www.pravda.com.ua/news/date_09022026/",
                   "https://www.pravda.com.ua/news/date_10022026/",
                   "https://www.pravda.com.ua/news/date_11022026/",
                   "https://www.pravda.com.ua/news/date_12022026/",
                   "https://www.pravda.com.ua/news/date_13022026/",
                   "https://www.pravda.com.ua/news/date_14022026/",
                   "https://www.pravda.com.ua/news/date_15022026/",
                   "https://www.pravda.com.ua/news/date_16022026/",
                   "https://www.pravda.com.ua/news/date_17022026/",
                   "https://www.pravda.com.ua/news/date_18022026/",
                   "https://www.pravda.com.ua/news/date_19022026/",
                   "https://www.pravda.com.ua/news/date_20022026/",
                   "https://www.pravda.com.ua/news/date_21022026/",
                   "https://www.pravda.com.ua/news/date_22022026/",
                   "https://www.pravda.com.ua/news/date_23022026/",
                   "https://www.pravda.com.ua/news/date_24022026/",
                   "https://www.pravda.com.ua/news/date_25022026/",
                   "https://www.pravda.com.ua/news/date_26022026/",
                   "https://www.pravda.com.ua/news/date_27022026/",
                   "https://www.pravda.com.ua/news/date_28022026/" ]
    
korrespondent_urls = ["https://ua.korrespondent.net/all/2026/february/8/", 
                        "https://ua.korrespondent.net/all/2026/february/9/",
                        "https://ua.korrespondent.net/all/2026/february/10/",
                        "https://ua.korrespondent.net/all/2026/february/11/",
                        "https://ua.korrespondent.net/all/2026/february/12/",
                        "https://ua.korrespondent.net/all/2026/february/13/",
                        "https://ua.korrespondent.net/all/2026/february/14/",
                        "https://ua.korrespondent.net/all/2026/february/15/",
                        "https://ua.korrespondent.net/all/2026/february/16/",
                        "https://ua.korrespondent.net/all/2026/february/17/",
                        "https://ua.korrespondent.net/all/2026/february/18/",
                        "https://ua.korrespondent.net/all/2026/february/19/",
                        "https://ua.korrespondent.net/all/2026/february/20/",
                        "https://ua.korrespondent.net/all/2026/february/21/",
                        "https://ua.korrespondent.net/all/2026/february/22/",
                        "https://ua.korrespondent.net/all/2026/february/23/",
                        "https://ua.korrespondent.net/all/2026/february/24/",
                        "https://ua.korrespondent.net/all/2026/february/25/",
                        "https://ua.korrespondent.net/all/2026/february/26/",
                        "https://ua.korrespondent.net/all/2026/february/27/",
                        "https://ua.korrespondent.net/all/2026/february/28/" ]
